### ISSUE TITLE
BasicAuth doesnt work

### ISSUE THREAD

**Issue by dormullor** [metrico/loki-action#4]
After my last PR, i have upgrade the action to V3 but still getting 401 from Loki when trying to send logs from pipeline

<img width="1054" alt="Screenshot 2023-08-30 at 13 25 42" src="https://github.com/metrico/loki-action/assets/105583031/d451dc39-710a-4a03-8447-f00d8a5c42de">

<img width="533" alt="Screenshot 2023-08-30 at 13 26 19" src="https://github.com/metrico/loki-action/assets/105583031/b64460e5-52a6-4e4b-8870-1958abd43751">

**Comment by lmangani** [comment]
are you using a local or cloud loki instance?

**Comment by dormullor** [comment]
local

**Comment by lmangani** [comment]
How does the action connect to the instance? If the request actually lands, Is the auth failure reflected in the Loki logs?

**Comment by dormullor** [comment]
As you can see at the Loki logs, the username and password are empty ( the first 2 dashes ).
I tried to trigger the action with hardcoded string username and password and it still empty

**Comment by lmangani** [comment]
@dormullor thanks for the confirmation 👍  let me try to reproduce this

**Comment by Dletta** [comment]
@dormullor I have create a PR that updates sub dependencies and I can confirm logs are received correctly.

One thing I found during my process was, that if you do not need user and password it is best not to add them to the secrets as an empty variable is different than a non-existing one.

**Comment by dormullor** [comment]
Perfect ! work like a charm 
Thanks !

**Comment by dormullor** [comment]
Perfect ! works like a charm
Thanks !
